/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DPIT121.Insurance_Policies1;

import javax.swing.JOptionPane;

/**
 *
 * @author Ali
 */
public class Edit extends javax.swing.JFrame {

    InsurancePolicy policy;
    UserUI userUi;
    
    
    int mYear;
    double price;
    int claim;
    int dayx;
    int monthx;
    int yearx;
    String cmodel;
    
    public Edit(InsurancePolicy policy, UserUI userUi) {
        initComponents();
        this.policy=policy;
        this.setVisible(true);
        this.userUi=userUi;
        this.userUi.setVisible(false);
        setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        model = new javax.swing.JPanel();
        headingAddPolicy = new javax.swing.JLabel();
        addPolicy = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        carYear = new javax.swing.JTextField();
        carPrice = new javax.swing.JTextField();
        carModel = new javax.swing.JTextField();
        carType = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        claims = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addPolicy.setText("Update");
        addPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPolicyActionPerformed(evt);
            }
        });

        jLabel10.setText("Car Details");

        jLabel11.setText("Model");

        jLabel12.setText("Manufactured Year");

        jLabel13.setText("Type");

        jLabel14.setText("Price");

        carType.setToolTipText("");

        jLabel15.setText("$");

        jLabel16.setText("Policy Details");

        jLabel17.setText("Number of Claims");

        jLabel18.setText("Expiry Date");

        jLabel19.setText("Day");

        jLabel20.setText("Month");

        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        jLabel21.setText("Year");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modelLayout = new javax.swing.GroupLayout(model);
        model.setLayout(modelLayout);
        modelLayout.setHorizontalGroup(
            modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modelLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(headingAddPolicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(44, 44, 44))
            .addGroup(modelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modelLayout.createSequentialGroup()
                        .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modelLayout.createSequentialGroup()
                                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addGap(90, 90, 90)
                                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(carPrice)
                                    .addComponent(carType, 0, 71, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(86, 86, 86)
                                .addComponent(carModel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(modelLayout.createSequentialGroup()
                        .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modelLayout.createSequentialGroup()
                                .addComponent(carYear)
                                .addContainerGap(563, Short.MAX_VALUE))
                            .addGroup(modelLayout.createSequentialGroup()
                                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(modelLayout.createSequentialGroup()
                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18)))
                    .addGroup(modelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel17)
                        .addGap(35, 35, 35)
                        .addComponent(claims, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(501, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addPolicy)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(69, 69, 69))
        );
        modelLayout.setVerticalGroup(
            modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingAddPolicy)
                    .addComponent(jButton2))
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(carModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(carType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(carPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(carYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(claims, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPolicy)
                    .addComponent(jButton1))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setValues()
    {
        mYear=policy.car.getManufacturingYear();
        price=policy.car.getPrice();
        claim=policy.numberOfClaims;
        dayx=policy.expiryDate.getDay();
        monthx=policy.expiryDate.getMonth();
        yearx=policy.expiryDate.getYear();
        cmodel = policy.getCarModel();
        
        
        carYear.setText(mYear+"");
        carPrice.setText(price+"");
        claims.setText(claim+"");
        day.setText(dayx+"");
        month.setText(monthx+"");
        year.setText(yearx+"");
        carModel.setText(cmodel+"");
        
        for (CarType type : CarType.values())
        {
            carType.addItem(type.toString());
        }
    }
    
    private void addPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPolicyActionPerformed
        // TODO add your handling code here:
        
        
        
        

        String model = carModel.getText();
        CarType type = CarType.valueOf(carType.getSelectedItem().toString());
        try{
            mYear = Integer.parseInt(carYear.getText());
        }catch(Exception e)
        {JOptionPane.showMessageDialog(this,"Invalid Manufacturing year entry try Again   "+e);}
        try{
            price = Double.valueOf(carPrice.getText());
        }catch(Exception e)
        {JOptionPane.showMessageDialog(this,"Invalid price entry try Again   "+e);}
        try{
            claim = Integer.parseInt(claims.getText());
        }catch(Exception e)
        {JOptionPane.showMessageDialog(this,"Invalid number of claims entry try Again   "+e);}
        try{
            dayx = Integer.parseInt(day.getText());
            monthx = Integer.parseInt(month.getText());
            yearx = Integer.parseInt(year.getText());
        }catch(Exception e)
        {JOptionPane.showMessageDialog(this,"Invalid Expiry Date entry try Again   "+e);}

        try{
            policy.update(new Car(model,mYear,price,type), new MyDate(yearx,monthx,dayx), claim);
            JOptionPane.showMessageDialog(this,"Updated Successfully");
            this.setVisible(false);
            userUi.setVisible(true);
        }catch(Exception e)
        {   JOptionPane.showMessageDialog(this,"Somthing went wrong while data entry   "+e);
        }
        
        clearPolicyTab();
    }//GEN-LAST:event_addPolicyActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearPolicyTab();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userUi.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
        public void clearPolicyTab()
    
    {
        carModel.setText("");
        carYear.setText("");
        carPrice.setText("");
        claims.setText("");
        day.setText("");
        month.setText("");
        year.setText("");
    
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPolicy;
    private javax.swing.JTextField carModel;
    private javax.swing.JTextField carPrice;
    private javax.swing.JComboBox<String> carType;
    private javax.swing.JTextField carYear;
    private javax.swing.JTextField claims;
    private javax.swing.JTextField day;
    private javax.swing.JLabel headingAddPolicy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel model;
    private javax.swing.JTextField month;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
